### ISSUE TITLE
Add usage to website.

### ISSUE THREAD

**Issue by jeena** [TypeTalk/TypeTalk#2]
While on OS X I had written my own app to use TTS so it would read longer articles while I was doing house chores, I called it Speaker https://github.com/jeena/Speaker

Now I moved compleatly to Linux and was looking for some similar app too, which would be easy to use. In https://opensource.com/life/15/8/interview-ken-starks-texas-linux-fest I found a direct link to a v0.2 jar download, from this I understood that I have to go to https://github.com/raginggoblin/speechless/ which let me to http://typetalk.github.io/TypeTalk/ where I was able to download the jar but didn't know how to start the app. Finally on https://github.com/TypeTalk/TypeTalk I was able to find the usage.

It would be nicer if you added the usage to the website too.

**Comment by raginggoblin** [comment]
Added (limited) instructions.

**Comment by jeena** [comment]
Very appreciated :)
