### ISSUE TITLE
Show where in the Text I am while reading

### ISSUE THREAD

**Issue by jeena** [TypeTalk/TypeTalk#3]
While on OS X I had written my own app to use TTS so it would read longer articles while I was doing house chores, I called it Speaker https://github.com/jeena/Speaker

What I miss from TypeTalk is the possibility to see where in the long text I am right now, when I press play it only makes the big text area non writable and that's it. In my app I was able to mark the word which was spoken right now with a yellow background, perhaps something like that is possible here too?

**Comment by raginggoblin** [comment]
This would be a nice addition. I cannot mark the word due to technical reasons, but marking the sentence would be possible.

**Comment by raginggoblin** [comment]
This is now available in v1.6

**Comment by jeena** [comment]
Finally I had the time to check this change out, this is awesome! Thank you very much, this makes it so much easier to use how I use it (reading long texts).
