### ISSUE TITLE
Make it possible to start reading from arbriary place in the text.

### ISSUE THREAD

**Issue by jeena** [TypeTalk/TypeTalk#4]
I'm mostly using the app to let it to read long articles out loud to me. It would be nice if I sometimes would be able to pause and later to continue. Even better it would be if it would start reading where the cursor is, so I can jump over parts and so on.

**Comment by raginggoblin** [comment]
It has been a long time since I could give a little love to this project. But in the end I think this is a valid improvement. It will be added in the next version.

**Comment by jeena** [comment]
Great to hear!

**Comment by raginggoblin** [comment]
See version 1.7
