### ISSUE TITLE
Add keyboard shortcut to stop

### ISSUE THREAD

**Issue by jeena** [TypeTalk/TypeTalk#5]
Thore is a keyboard shortcut to play the text `Ctrl+p` but there is none to stop, you have to use your mouse to press the stop button.

**Comment by raginggoblin** [comment]
Missed that one, thanks. I will add it in the next version as the play and stop button toggles, it will have the same shortcut `Ctrl+p`.

**Comment by jeena** [comment]
Great thanks!
